version: 2

aliases:
  # -------------------------
  #      ALIASES: Caches
  # -------------------------
  - &restore-deps-cache-ubuntu
    key: rust-cache-{{ arch }}-{{ checksum "Cargo.lock" }}-{{ .Environment.CIRCLE_JOB }}

  - &save-deps-cache-ubuntu
    key: rust-cache-{{ arch }}-{{ checksum "Cargo.lock" }}-{{ .Environment.CIRCLE_JOB }}
    paths:
      - /usr/local/cargo/registry
      - /usr/local/rustup
      - ~/project/target/

  - &restore-deps-cache-rustup
    key: rust-cache-musl-{{ arch }}-{{ checksum "Cargo.lock" }}-{{ .Environment.CIRCLE_JOB }}

  - &save-deps-cache-rustup
    key: rust-cache-musl-{{ arch }}-{{ checksum "Cargo.lock" }}-{{ .Environment.CIRCLE_JOB }}
    paths:
      - ~/.rustup/
      - ~/.cargo/
      - ~/project/target/
  # -------------------------
  # ALIASES: Utility commands DRY
  - &setup-docker
    name: Setup docker environment
    command: |
      export DOCKERVERSION="18.09.6"
      curl -fsSLO https://download.docker.com/linux/static/stable/x86_64/docker-${DOCKERVERSION}.tgz
      tar xzvf docker-${DOCKERVERSION}.tgz --strip 1 -C /usr/local/bin docker/docker
      rm docker-${DOCKERVERSION}.tgz
      docker --version


defaults: &defaults
  working_directory: ~/project
  environment:
    RUST_BACKTRACE: 1

jobs:
  codecov:
    <<: *defaults
    machine: true
    steps:
      - checkout
      - restore_cache: *restore-deps-cache-rustup
      - run:
          name: Install Rust
          command: |
            curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly -y
            echo 'export PATH=$HOME/.cargo/bin:$PATH' >> $BASH_ENV
      - run:
          name: Install Tarpaulin
          command: cargo tarpaulin --version || cargo install cargo-tarpaulin
          environment:
            RUSTFLAGS: --cfg procmacro2_semver_exempt
      - run:
          name: Generate coverage report
          command: cargo tarpaulin -v --out Xml --all-features
      - save_cache: *save-deps-cache-rustup
      - run:
          name: Upload to codecov.io
          command: bash <(curl -s https://codecov.io/bash) -Z -f cobertura.xml

  build:
    <<: *defaults
    docker:
      - image: clux/muslrust:nightly
    steps:
      - checkout
      - restore_cache: *restore-deps-cache-rustup
      - run: rustup target add x86_64-unknown-linux-musl
      - run: cargo build --release
      - save_cache: *save-deps-cache-rustup
      - run:
          name: Move binaries into bin/ directory
          command: |
            mkdir bin/
            mv target/x86_64-unknown-linux-musl/release/semanteecore ./bin/semanteecore
      - persist_to_workspace:
          root: .
          paths:
            - bin/*

  release-dry:
    <<: *defaults
    docker:
      - image: rust:latest
    steps:
      - setup_remote_docker
      - run: *setup-docker
      - checkout
      - attach_workspace:
          at: /workspace
      - restore_cache: *restore-deps-cache-ubuntu
      - run: /workspace/bin/semanteecore --dry
      - save_cache: *save-deps-cache-ubuntu

  release:
    <<: *defaults
    docker:
      - image: rust:latest
    steps:
      - setup_remote_docker
      - run: *setup-docker
      - checkout
      - attach_workspace:
          at: /workspace
      - restore_cache: *restore-deps-cache-ubuntu
      # This unset is VERY important: without it --force-https cannot work
      # For some reason CircleCI has a global override substituting git@ links instead of all https links
      - run: git config --global --unset url.ssh://git@github.com.insteadof
      - run: /workspace/bin/semanteecore
      - save_cache: *save-deps-cache-ubuntu

  rebase_develop_onto_master:
    <<: *defaults
    docker:
      - image: alpine/git:latest
    steps:
      - checkout
      - run:
          name: Configure git
          command: |
            git config --global user.email "$GIT_COMMITTER_EMAIL"
            git config --global user.name "$GIT_COMMITTER_NAME"
            git config --global --unset url.ssh://git@github.com.insteadof
      - run:
          name: Actualize master branch
          command: |
            git checkout master
            git pull origin master
      - run:
          name: Rebase develop -> master
          command: |
            git checkout develop
            git rebase master
      - run:
          name: Push changes
          command: |
            git remote set-url origin https://mersinvald:$GH_TOKEN@github.com/semanteecore/semanteecore.git --push
            git remote set-url origin https://mersinvald:$GH_TOKEN@github.com/semanteecore/semanteecore.git
            git checkout develop
            git push origin develop

workflows:
  version: 2
  ci:
    jobs:
      - codecov
      - build:
          filters:
            branches:
              only:
                - staging
                - trying
      - release-dry:
          requires:
            - build
      - release:
          filters:
            branches:
              only: master
          requires:
            - build
      - rebase_develop_onto_master:
          filters:
            branches:
              only: master
          requires:
            - release